[pytest]

python_files = test_*.py
python_classes = Test*
python_functions = test_*

testpaths = tests

addopts =
    -v
    --tb=short
    --html=reports/report.html
    --self-contained-html

markers =
    hallucination: hallucination testing
