from pathlib import Path

import pandas as pd


class QABoatExcelLoader:
    """
    Loads test cases generated by QA Boat from an exported Excel file.

    Responsibility:
        QA Boat Excel -> common generated test-case structure

    This class does NOT perform:
        - Schema validation
        - Test-case quality validation
        - Coverage validation
        - DeepEval evaluation
        - Scoring
    """

    SHEET_NAME = "Task Test Cases"

    REQUIRED_COLUMNS = [
        "Task ID",
        "Task Name",
        "Test ID",
        "Scenario",
        "Title",
        "Preconditions",
        "Steps",
        "Expected",
        "Refs",
    ]

    @classmethod
    def load(cls, file_path: str | Path) -> dict:

        file_path = Path(file_path)

        if not file_path.exists():
            raise FileNotFoundError(
                f"QA Boat Excel file not found: {file_path}"
            )

        dataframe = pd.read_excel(
            file_path,
            sheet_name=cls.SHEET_NAME,
        )

        # Remove completely empty rows
        dataframe = dataframe.dropna(
            how="all"
        ).copy()

        # Check required columns
        missing_columns = [
            column
            for column in cls.REQUIRED_COLUMNS
            if column not in dataframe.columns
        ]

        if missing_columns:
            raise ValueError(
                "QA Boat Excel is missing required columns: "
                f"{missing_columns}"
            )

        # QA Boat only populates Task ID / Task Name
        # on the first row of each task.
        dataframe["Task ID"] = dataframe[
            "Task ID"
        ].ffill()

        dataframe["Task Name"] = dataframe[
            "Task Name"
        ].ffill()

        test_cases = []

        for _, row in dataframe.iterrows():

            test_id = cls._to_text(
                row["Test ID"]
            )

            # Ignore rows that are not test cases
            if not test_id:
                continue

            test_case = {
                # Common evaluator fields
                "testCaseId": test_id,

                "testDescription": cls._to_text(
                    row["Title"]
                ),

                "testSteps": cls._parse_steps(
                    row["Steps"]
                ),

                "expectedResult": cls._to_text(
                    row["Expected"]
                ),

                # QA Boat metadata
                "taskId": cls._to_text(
                    row["Task ID"]
                ),

                "taskName": cls._to_text(
                    row["Task Name"]
                ),

                "scenario": cls._to_text(
                    row["Scenario"]
                ),

                "preconditions": cls._to_text(
                    row["Preconditions"]
                ),

                "refs": cls._to_text(
                    row["Refs"]
                ),
            }

            test_cases.append(
                test_case
            )

        return {
            "testCases": test_cases
        }

    @staticmethod
    def _to_text(value) -> str:

        if pd.isna(value):
            return ""

        return str(value).strip()

    @classmethod
    def _parse_steps(cls, value) -> list[str]:

        text = cls._to_text(value)

        if not text:
            return []

        lines = text.splitlines()

        steps = []

        for line in lines:

            line = line.strip()

            if not line:
                continue

            # Remove common numbering:
            # 1. Step
            # 2) Step
            # 3 - Step

            if ". " in line:

                prefix, remainder = line.split(
                    ". ",
                    1,
                )

                if prefix.strip().isdigit():
                    line = remainder.strip()

            elif ") " in line:

                prefix, remainder = line.split(
                    ") ",
                    1,
                )

                if prefix.strip().isdigit():
                    line = remainder.strip()

            elif " - " in line:

                prefix, remainder = line.split(
                    " - ",
                    1,
                )

                if prefix.strip().isdigit():
                    line = remainder.strip()

            if line:
                steps.append(line)

        if not steps:
            steps.append(text)

        return steps