import json
from pathlib import Path
from datetime import datetime

from config.settings import OUTPUT_FOLDER


class GeneratedJsonStorage:
    """
    Saves and loads the raw JSON generated by the LLM.

    IMPORTANT
    ---------
    This class stores the original QA Boat / Qwen3 output
    without modifying its structure.

    Expected generated JSON:

    {
        "testCases": [
            {
                "testCaseId": "...",
                "testDescription": "...",
                "testSteps": [],
                "expectedResult": "..."
            }
        ]
    }

    Evaluation-specific information such as requirement
    mapping, benchmark mapping, validation and DeepEval
    results must NOT be added here.
    """

    GENERATED_FOLDER = (
        Path(OUTPUT_FOLDER)
        / "generated"
    )

    # ======================================================
    # Save Raw Generated JSON
    # ======================================================

    @staticmethod
    def save(
        *,
        provider: str,
        requirement_id: str,
        response,
    ) -> Path:

        folder = (
            GeneratedJsonStorage.GENERATED_FOLDER
            / provider
        )

        folder.mkdir(
            parents=True,
            exist_ok=True,
        )

        timestamp = datetime.now().strftime(
            "%Y%m%d_%H%M%S"
        )

        file_path = (
            folder
            / f"{requirement_id}_{timestamp}.json"
        )

        # --------------------------------------------------
        # Response already parsed as dictionary
        # --------------------------------------------------

        if isinstance(response, dict):

            with open(
                file_path,
                "w",
                encoding="utf-8",
            ) as file:

                json.dump(
                    response,
                    file,
                    indent=4,
                    ensure_ascii=False,
                )

            return file_path

        # --------------------------------------------------
        # Response returned as JSON string
        # --------------------------------------------------

        try:

            parsed = json.loads(response)

            with open(
                file_path,
                "w",
                encoding="utf-8",
            ) as file:

                json.dump(
                    parsed,
                    file,
                    indent=4,
                    ensure_ascii=False,
                )

        except json.JSONDecodeError:

            # Preserve the raw response exactly if it
            # cannot be parsed as JSON.
            with open(
                file_path,
                "w",
                encoding="utf-8",
            ) as file:

                file.write(response)

        return file_path

    # ======================================================
    # Load Raw Generated JSON
    # ======================================================

    @staticmethod
    def load(
        file_path: Path,
    ) -> dict:

        with open(
            file_path,
            "r",
            encoding="utf-8",
        ) as file:

            return json.load(file)